services:
  api:
    build:
      context: .
      dockerfile: GameStore.Api/Dockerfile
    ports:
      - "5000:8080"
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Data Source=/app/data/GameStore.db

  frontend:
    build:
      context: .
      dockerfile: GameStore.Frontend/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GameStoreApiUrl=http://api:8080
